name: publish

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read
  pull-requests: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:14.19.1-alpine
    steps:
      - uses: actions/checkout@v4

      - name: Install Python 3
        run: |
          apk add --no-cache python2 py-pip make g++

      - name: Install dependencies
        run: npm install
        env:
          NPM_GITHUB_READ: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepublish
        run: npm run prepare
        env:
          NPM_GITHUB_READ: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        run: |
          npm publish
          echo "-- build completed successfully"
        env:
          NPM_GITHUB_READ: ${{ secrets.GITHUB_TOKEN }}
